<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit7bd8fe3cd8e5332ad3a973166c329026
{
    public static $prefixLengthsPsr4 = array (
        'W' => 
        array (
            'WooCommerceMinMaxQuantities\\ByteKit\\' => 36,
            'WooCommerceMinMaxQuantities\\' => 28,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'WooCommerceMinMaxQuantities\\ByteKit\\' => 
        array (
            0 => __DIR__ . '/..' . '/byteever/bytekit-settings/src',
            1 => __DIR__ . '/..' . '/byteever/bytekit-plugin/src',
        ),
        'WooCommerceMinMaxQuantities\\' => 
        array (
            0 => __DIR__ . '/../..' . '/includes',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
        'WooCommerceMinMaxQuantities\\Admin\\Actions' => __DIR__ . '/../..' . '/includes/Admin/Actions.php',
        'WooCommerceMinMaxQuantities\\Admin\\Admin' => __DIR__ . '/../..' . '/includes/Admin/Admin.php',
        'WooCommerceMinMaxQuantities\\Admin\\MetaBoxes' => __DIR__ . '/../..' . '/includes/Admin/MetaBoxes.php',
        'WooCommerceMinMaxQuantities\\Admin\\Notices' => __DIR__ . '/../..' . '/includes/Admin/Notices.php',
        'WooCommerceMinMaxQuantities\\Admin\\Settings' => __DIR__ . '/../..' . '/includes/Admin/Settings.php',
        'WooCommerceMinMaxQuantities\\ByteKit\\Admin\\Flash' => __DIR__ . '/..' . '/byteever/bytekit-plugin/src/Admin/Flash.php',
        'WooCommerceMinMaxQuantities\\ByteKit\\Admin\\Notices' => __DIR__ . '/..' . '/byteever/bytekit-plugin/src/Admin/Notices.php',
        'WooCommerceMinMaxQuantities\\ByteKit\\Admin\\Settings' => __DIR__ . '/..' . '/byteever/bytekit-settings/src/Admin/Settings.php',
        'WooCommerceMinMaxQuantities\\ByteKit\\Interfaces\\Pluginable' => __DIR__ . '/..' . '/byteever/bytekit-plugin/src/Interfaces/Pluginable.php',
        'WooCommerceMinMaxQuantities\\ByteKit\\Interfaces\\Scriptable' => __DIR__ . '/..' . '/byteever/bytekit-plugin/src/Interfaces/Scriptable.php',
        'WooCommerceMinMaxQuantities\\ByteKit\\Plugin' => __DIR__ . '/..' . '/byteever/bytekit-plugin/src/Plugin.php',
        'WooCommerceMinMaxQuantities\\ByteKit\\Scripts' => __DIR__ . '/..' . '/byteever/bytekit-plugin/src/Scripts.php',
        'WooCommerceMinMaxQuantities\\ByteKit\\Services' => __DIR__ . '/..' . '/byteever/bytekit-plugin/src/Services.php',
        'WooCommerceMinMaxQuantities\\ByteKit\\Traits\\HasPlugin' => __DIR__ . '/..' . '/byteever/bytekit-plugin/src/Traits/HasPlugin.php',
        'WooCommerceMinMaxQuantities\\Cart' => __DIR__ . '/../..' . '/includes/Cart.php',
        'WooCommerceMinMaxQuantities\\Installer' => __DIR__ . '/../..' . '/includes/Installer.php',
        'WooCommerceMinMaxQuantities\\Plugin' => __DIR__ . '/../..' . '/includes/Plugin.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit7bd8fe3cd8e5332ad3a973166c329026::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit7bd8fe3cd8e5332ad3a973166c329026::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit7bd8fe3cd8e5332ad3a973166c329026::$classMap;

        }, null, ClassLoader::class);
    }
}
