<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'Composer\\InstalledVersions' => $vendorDir . '/composer/InstalledVersions.php',
    'WooCommerceMinMaxQuantities\\Admin\\Actions' => $baseDir . '/includes/Admin/Actions.php',
    'WooCommerceMinMaxQuantities\\Admin\\Admin' => $baseDir . '/includes/Admin/Admin.php',
    'WooCommerceMinMaxQuantities\\Admin\\MetaBoxes' => $baseDir . '/includes/Admin/MetaBoxes.php',
    'WooCommerceMinMaxQuantities\\Admin\\Notices' => $baseDir . '/includes/Admin/Notices.php',
    'WooCommerceMinMaxQuantities\\Admin\\Settings' => $baseDir . '/includes/Admin/Settings.php',
    'WooCommerceMinMaxQuantities\\ByteKit\\Admin\\Flash' => $vendorDir . '/byteever/bytekit-plugin/src/Admin/Flash.php',
    'WooCommerceMinMaxQuantities\\ByteKit\\Admin\\Notices' => $vendorDir . '/byteever/bytekit-plugin/src/Admin/Notices.php',
    'WooCommerceMinMaxQuantities\\ByteKit\\Admin\\Settings' => $vendorDir . '/byteever/bytekit-settings/src/Admin/Settings.php',
    'WooCommerceMinMaxQuantities\\ByteKit\\Interfaces\\Pluginable' => $vendorDir . '/byteever/bytekit-plugin/src/Interfaces/Pluginable.php',
    'WooCommerceMinMaxQuantities\\ByteKit\\Interfaces\\Scriptable' => $vendorDir . '/byteever/bytekit-plugin/src/Interfaces/Scriptable.php',
    'WooCommerceMinMaxQuantities\\ByteKit\\Plugin' => $vendorDir . '/byteever/bytekit-plugin/src/Plugin.php',
    'WooCommerceMinMaxQuantities\\ByteKit\\Scripts' => $vendorDir . '/byteever/bytekit-plugin/src/Scripts.php',
    'WooCommerceMinMaxQuantities\\ByteKit\\Services' => $vendorDir . '/byteever/bytekit-plugin/src/Services.php',
    'WooCommerceMinMaxQuantities\\ByteKit\\Traits\\HasPlugin' => $vendorDir . '/byteever/bytekit-plugin/src/Traits/HasPlugin.php',
    'WooCommerceMinMaxQuantities\\Cart' => $baseDir . '/includes/Cart.php',
    'WooCommerceMinMaxQuantities\\Installer' => $baseDir . '/includes/Installer.php',
    'WooCommerceMinMaxQuantities\\Plugin' => $baseDir . '/includes/Plugin.php',
);
